deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk update && apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_ed25519
    - chmod 400 ~/.ssh/id_ed25519
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

  script:
    - ssh-add ~/.ssh/id_ed25519
    - ssh ${SSH_USER}@${SSH_HOST} "cd /var/www/www.arnaud-roseo.com/ && git checkout master && git pull origin master && exit"
    - /bin/sh
  only:
    - master
